config/routes.rb
Rails.application.routes.draw do

  get 'home', to: "posts#index", as: "home"
  root to: "user#index"



  devise_for :user,controllers: {
    registrations: 'user/registrations'
  }

  devise_scope :user do
    get 'login',to: 'devise/sessions#new'
    get 'logout',to: 'devise/sessions#destroy'
    get 'sign_up',to: 'devise/registrations#new'
  end


  scope '/user' do
    get '', to: "user#index", as: "users"
    get '/:id', to:"user#show", as: "user"
    get '/:id/posts', to:"user#posts", as:"user_posts"
    get '/:id/followers', to:"user#followers", as:"user_followers"
    put '/follow/:id',to: "user#follow_unfollow_user", as:"follow_unfollow_user"

  end

  scope '/posts' do
    post '',to: 'posts#create',as:"posts"
    get '/new',to:"posts#new",as: "new_post"
    put ':id/like_post',to:"posts#like_post",as:"like_post"
  end



end

app/views/shared/_footer.html.erb
<footer class="page-footer blue lighten-3">
  <div class="footer-copyright">
    <div class="container left" id="copyright">
       © <%= Time.now.year.to_s %> Aldo Cid Siqueira</div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="light-blue accent-1">
  <div class="nav-wrapper">

    <%= link_to 'Home',home_path,class:"brand-logo center"%>
    <% if user_signed_in? %>

      <ul id="nav-right-mobile"class="right hide-on-med-and-down">

        <li class="light-blue accent-1" >
          <%= link_to @current_user, method: :get do %>
          Perfil<i class="material-icons right">perm_identity</i>
          <% end %>
        </li>

        <li class="red lighten-3" >
          <%= link_to destroy_user_session_path, method: :delete do %>
          Sair<i class="material-icons right">power_settings_new</i>
          <% end %>
        </li>
      </ul>

    <% else %>
      <ul id="nav-right-mobile"class="right hide-on-med-and-down">

        <li>
          <%= link_to sign_up_path, method: :get do %>
          Cadastrar<i class="material-icons right">input</i>
          <% end %>
        </li>
        <li class="blue lighten-2" >
          <%= link_to new_user_session_path, method: :get do %>
          Entrar<i class="material-icons right">power_settings_new</i>
          <% end %>
        </li>

      </ul>
    <% end%>

  </div>
</nav>
</header>

app/views/shared/_notice_message.html.erb
<% if notice %>
  <p id="notice" style="color:#60b354">
    <%= notice %>
  </p>
<% end %>