config/routes.rb
Rails.application.routes.draw do

  get 'home', to: "posts#index", as: "home"
  root to: "user#index"



  devise_for :user,controllers: {
    registrations: 'user/registrations'
  }

  devise_scope :user do
    get 'login',to: 'devise/sessions#new'
    get 'logout',to: 'devise/sessions#destroy'
    get 'sign_up',to: 'devise/registrations#new'
  end


  scope '/user' do
    get '', to: "user#index", as: "users"
    get '/:id', to:"user#show", as: "user"
    get '/:id/posts', to:"user#posts", as:"user_posts"
    get '/:id/followers', to:"user#followers", as:"user_followers"
    put '/follow/:id',to: "user#follow_unfollow_user", as:"follow_unfollow_user"

  end

  scope '/posts' do
    post '',to: 'posts#create',as:"posts"
    get '/new',to:"posts#new",as: "new_post"
    put ':id/like_post',to:"posts#like_post",as:"like_post"
  end



end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_and_belongs_to_many :followers,class_name:"User",
                                    join_table:"followers",
                                    association_foreign_key: "follower_id"

  has_attached_file :avatar, styles: { medium: "300x300>" ,thumb: "100x100"}
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def follows?(user)
    self.followers.include?(user)
  end

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:avatar])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, except:[:index]
  
  #GET user
  def index
    if params[:search_field]
      @users = User.where('name LIKE ?',"%#{params[:search_field]}")
    else
      @users = []
    end
  end

  #GET user/:id
  def show
  end

  #GET user/:id/followers
  def followers
    @user_followers = @user.followers
  end

  #GET user/:id/posts
  def posts
    @user_posts = @user.posts.order(created_at: :desc)
  end

  #GET user/follow:id
  def follow_unfollow_user
    if !@current_user.follows?(@user)
      @current_user.followers << @user
    else
      @current_user.followers.delete(@user)
    end
    redirect_to user_url(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/followers.html.erb
<h2>Seguidores de <%= @user.name %></h2>
<table class="highlight">
  <thead>
    <tr>
      <th data-field="user">Avatar</th>
      <th data-field="name">Name</th>
      <th data-field="email">Email</th>
      <th data-field="followers">Followers</th>
    </tr>
  </thead>
  <tbody>
    <% @user_followers.each do |user| %>
      <tr>
        <td><%= image_tag user.avatar.url(:thumb),class:"circle responsive-img" %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.followers.size %></td>
        <%= hidden_field_tag "", user_path(user), class: "tr_link" %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user/index.html.erb
<%= form_tag(users_path, method: :get) do %>
  <ul class="inline center">
    <li>
      <%= text_field_tag 'search_field',nil, placeholder: 'Buscar por usuário',style:"width: 70%;"%>
    </li>
    <li>
      <%= submit_tag 'Buscar' ,class: "waves-effect waves-light btn amber lighten-1"%>
    </li>
  </ul>
<% end %>

<table class="highlight">
  <thead>
    <tr>
      <th data-field="user">Avatar</th>
      <th data-field="user">Name</th>
      <th data-field="rental_time">Email</th>
      <th data-field="rental_time">Seguidores</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.avatar.url(:thumb),class:"circle responsive-img" %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.followers.size %></td>
        <%= hidden_field_tag "", user_path(user), class: "tr_link" %>
      </tr>
    <% end %>
  </tbody>
</table>


<% if user_signed_in? %>
<div class="fixed-action-btn" style="bottom: 60px; right: 24px;">
  <%= link_to new_post_path, class: "btn-floating btn-large amber lighten-1" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>
<% end %>

app/views/user/posts.html.erb
<%  if @current_user.id == @user.id %>
  <h2 class="center">Suas postagens</h2>
<% else %>
  <h2 class="center">Postagens de <%= @user.name%></h2>
<% end %>
<% if @user_posts.size > 0 %>
  <% @user_posts.each do |post|%>
    <div class="row">
        <div class="col s12">
              <div class="card light-blue lighten-3 ">
                <div class="card-content dark-text">
                  <div class="card__meta">
                  <%= link_to @user.name,@user %>
                            <time><%= post.created_at.strftime('%v')%></time>
                </div>
                  <br>
                  <p><%= post.description%></p>
                  <br>
                  <p><%= post.n_likes%> curtidas</p>
                </div>
                <% if !(@current_user.id == @user.id) %>
                  <div class="card-action light-blue lighten-2">
                    <%= link_to like_post_url(post),method: :put,class:"amber lighten-1 btn" do %>
                      CURTIR<i class="material-icons left">thumb_up</i>
                    <% end %>
                  </div>
                <% end %>
            </div>
          </div>
      </div>
     </div>  
  <% end %>
<% end %>

<% if user_signed_in? && @current_user.id == @user.id %>
<div class="fixed-action-btn" style="bottom: 60px; right: 24px;">
  <%= link_to new_post_path, class: "btn-floating btn-large amber lighten-1" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>
<% end %>

app/views/user/show.html.erb
<div class="card">
  <div class="card-header light-blue lighten-3">
    <br>
      <div class="center">
          <%= image_tag @user.avatar.url(:medium),class:"circle responsive-img" %>
      </div>
    <br>
    <div class="center flow-text">
      <%= @user.name %>
    </div>
  </div>
  <div class="card-content teal lighten-4">
    <ul class="inline center">
      <li>

        <%= link_to user_posts_path,method: :get,class:"waves-effect waves-light btn amber lighten-1" do %>
          Postagens<i class="material-icons left">dashboard</i>
        <% end %>

    </li>
      <li>

        <%= link_to user_followers_path,method: :get,class:"waves-effect waves-light btn amber lighten-1" do %>
          Seguidores<i class="material-icons left">supervisor_account</i>
        <% end %>

      </li>
      <li>
        <% if user_signed_in? %>

          <% if @current_user.id == @user.id %>
            
            <%= link_to edit_user_registration_path,method: :get,class:"waves-effect waves-light btn amber lighten-1" do %>
              Editar<i  class="material-icons left">mode_edit</i>
            <% end %>

          <% else %>

            <% if @current_user.follows?(@user) %>

              <%= link_to follow_unfollow_user_path(@user),method: :put,class:"waves-effect waves-light light-green darken-1 btn", onclick: "$('#follow_form').submit()" do %>
                Seguindo<i class="material-icons right">done</i>
              <% end %>

            <% else %>

              <%= link_to follow_unfollow_user_path(@user),method: :put,class:"waves-effect waves-light light-blue accent-3 btn", onclick: "$('#follow_form').submit()" do %>
                  Seguir<i class="material-icons right">add</i>
              <% end %>
              
            <% end %>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/user/show_profile.html.erb
<div class="card">
  <div class="card-header light-blue lighten-3">
    <br>
      <div class="center">
          <%= image_tag @user.avatar.url(:medium),class:"circle responsive-img" %>
      </div>
    <br>
    <div class="center flow-text">
      <%= @user.name %>
    </div>
  </div>
  <div class="card-content teal lighten-4">
    <ul class="inline center">
      <li>
      <%= link_to show_user_posts_path,method: :get,class:"waves-effect waves-light btn amber lighten-1" do %>
      Postagens<i class="material-icons left">dashboard</i>
      <% end %>
    </li>
      <li>
        <%= link_to show_user_followers_path,method: :get,class:"waves-effect waves-light btn amber lighten-1" do %>
          Seguidores<i class="material-icons left">supervisor_account</i>
        <% end %>
      </li>
      <li>
        <% if user_signed_in? %>
        <% if @current_user.id == @user.id %>
          <%= link_to edit_user_registration_path,method: :get,class:"waves-effect waves-light btn amber lighten-1" do %>
            Editar<i  class="material-icons left">mode_edit</i>
          <% end %>
        <% else %>
            <% if @current_user.follows?(@user) %>
              <%= link_to follow_unfollow_user_path(@user),method: :put,class:"waves-effect waves-light light-green darken-1 btn", onclick: "$('#follow_form').submit()" do %>
                Seguindo<i class="material-icons right">done</i>
              <% end %>
            <% else %>
              <%= link_to follow_unfollow_user_path(@user),method: :put,class:"waves-effect waves-light light-blue accent-3 btn", onclick: "$('#follow_form').submit()" do %>
                Seguir<i class="material-icons right">add</i>
              <% end %>
            <% end %>
          <% end %>
          <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/user/show_user_followers.html.erb
<h2>Seguidores de <%= @user.name %></h2>
<table class="highlight">
  <thead>
    <tr>
      <th data-field="user">Avatar</th>
      <th data-field="name">Name</th>
      <th data-field="email">Email</th>
      <th data-field="followers">Followers</th>
    </tr>
  </thead>
  <tbody>
    <% @user_followers.each do |user| %>
      <tr>
        <td><%= image_tag user.avatar.url(:thumb),class:"circle responsive-img" %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.followers.size %></td>
        <%= hidden_field_tag "", user_path(user), class: "tr_link" %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user/show_user_posts.html.erb
<%  if @current_user.id == @user.id %>
  <h2 class="center">Suas postagens</h2>
<% else %>
  <h2 class="center">Postagens de <%= @user.name%></h2>
<% end %>
<% if @user_posts.size > 0 %>
  <% @user_posts.each do |post|%>
    <div class="row">
        <div class="col s12">
              <div class="card light-blue lighten-3 ">
                <div class="card-content dark-text">
                  <div class="card__meta">
                  <%= link_to @user.name,@user %>
                            <time><%= post.created_at.strftime('%v')%></time>
                </div>
                  <br>
                  <p><%= post.description%></p>
                  <br>
                  <p><%= post.n_likes%> curtidas</p>
                </div>
                <% if !(@current_user.id == @user.id) %>
                  <div class="card-action light-blue lighten-2">
                    <%= link_to like_post_url(post),method: :put,class:"amber lighten-1 btn" do %>
                      CURTIR<i class="material-icons left">thumb_up</i>
                    <% end %>
                  </div>
                <% end %>
            </div>
          </div>
      </div>
     </div>  
  <% end %>
<% end %>

<% if user_signed_in? && @current_user.id == @user.id %>
<div class="fixed-action-btn" style="bottom: 60px; right: 24px;">
  <%= link_to new_post_path, class: "btn-floating btn-large amber lighten-1" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>
<% end %>