config/routes.rb
Rails.application.routes.draw do

  get 'home', to: "posts#index", as: "home"
  root to: "user#index"



  devise_for :user,controllers: {
    registrations: 'user/registrations'
  }

  devise_scope :user do
    get 'login',to: 'devise/sessions#new'
    get 'logout',to: 'devise/sessions#destroy'
    get 'sign_up',to: 'devise/registrations#new'
  end


  scope '/user' do
    get '', to: "user#index", as: "users"
    get '/:id', to:"user#show", as: "user"
    get '/:id/posts', to:"user#posts", as:"user_posts"
    get '/:id/followers', to:"user#followers", as:"user_followers"
    put '/follow/:id',to: "user#follow_unfollow_user", as:"follow_unfollow_user"

  end

  scope '/posts' do
    post '',to: 'posts#create',as:"posts"
    get '/new',to:"posts#new",as: "new_post"
    put ':id/like_post',to:"posts#like_post",as:"like_post"
  end



end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :description, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :like_post]

  # GET /posts
  def index
    if params[:search_field]
      @users_search = User.where('name LIKE ?',"%#{params[:search_field]}")
    else
      @users_search = []
    end
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.user = @current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to user_posts_url(@current_user), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  def like_post
    @post.update(n_likes: @post.n_likes + 1)
    redirect_to user_posts_url(@post.user)
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<h2>Criar postagem</h2>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, autofocus: true %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit "Postar" ,class:"waves-effect waves-light amber lighten-1 btn"%>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= form_tag(home_path, method: :get) do %>
  <ul class="inline center">
    <li>
      <%= text_field_tag 'search_field',nil, placeholder: 'Buscar por usuário',style:"width: 70%;"%>
    </li>
    <li>
      <%= submit_tag 'Buscar' ,class: "waves-effect waves-light btn amber lighten-1"%>
    </li>
  </ul>
<% end %>

<table class="highlight">
  <thead>
    <tr>
      <th data-field="user">Avatar</th>
      <th data-field="user">Name</th>
      <th data-field="rental_time">Email</th>
      <th data-field="rental_time">Seguidores</th>
    </tr>
  </thead>
  <tbody>
    <% @users_search.each do |user| %>
      <tr>
        <td><%= image_tag user.avatar.url(:thumb),class:"circle responsive-img" %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.followers.size %></td>
        <%= hidden_field_tag "", user_path(user), class: "tr_link" %>
      </tr>
    <% end %>
  </tbody>
</table>


<% if user_signed_in? %>
<div class="fixed-action-btn" style="bottom: 60px; right: 24px;">
  <%= link_to new_post_path, class: "btn-floating btn-large amber lighten-1" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>